### PR TITLE
Fix and improve handling of -j flag

### LINKED ISSUE #1128: -j option weirdness with the compiler
Currently how the `-j` option works with the compiler is:
* If you specify `-j n` where n > 1, then the compiler will generate a parallel executable (with the `ParallelTransformer`transformer) which includes the `pfor` macro doing OpenMP stuff. Then, during runtime, you can specify any number of threads (`./compiled_souffle_program -j 123`). 
* If you specify `-j 1`, then the `pfor` macro is not generated, and also the `omp_set_num_threads` call is not generated. In this case, you can still do `./compiled_souffle_program -j 123`, but it won't do anything
* If you specify `-j auto`, then internally it converts it to `-j 0`, which makes the compiler do the same as `-j 1` (as far as I can tell). This doesn't match what it says in the help menu

It would be nice to clean this up and document it better.

There is another thing that might be nice to have with embedded souffle. Currently, if you generate a `.cpp` file with souffle (`souffle -g souffle_program -j 2`) and then try to use it embedded in something else, the souffle-generated part will always call `omp_set_num_threads(2)`, and there is no way of setting the number of threads for at runtime. It might be nice to allow the client code to call `omp_set_num_threads` to set the number of threads at runtime.

### PR DESCRIPTION
**Pull request by mmcgr**
Fixes #1128 
ParallelTransformer is run for all parallel programs
Number of threads can be configured by embedded souffle
Responsibility for setting number of threads in compiled code is moved from option parsing to the souffle program.

### CODE REVIEW

File: src/SouffleInterface.h [hunk 1]
```diff
@@ -285,6 +287,16 @@ class SouffleProgram {
     // dump output relations (for debug purposes)
     virtual void dumpOutputs(std::ostream& out = std::cout) = 0;
 
+    // Set the number of threads to be used
+    virtual void setNumThreads(std::size_t numThreads) {
```
Comment (lyndonhenry) [inline src/SouffleInterface.h]: Should not be virtual, also below.

File: src/Synthesiser.cpp [hunk 2]
```diff
@@ -2317,17 +2316,18 @@ void Synthesiser::generateCode(std::ostream& os, const std::string& id, bool& wi
...
     os << "souffle::";
     if (Global::config().has("profile")) {
         os << classname + " obj(opt.getProfileName());\n";
     } else {
         os << classname + " obj;\n";
     }
 
+    os << "#if defined(_OPENMP) \n";
+    os << "obj.setNumThreads(opt.getNumJobs());\n";
+    os << "omp_set_nested(true);\n";
```
Comment (lyndonhenry) [inline src/Synthesiser.cpp]: Do we need nesting? It may be better without, though this depends on if we do use nesting or not currently.

File: src/main.cpp [hunk 3]
```diff
@@ -245,30 +245,25 @@ int main(int argc, char** argv) {
...
+            if (!Global::config().has("jobs", "auto")) {
+                throw std::runtime_error(
+                        "Wrong parameter " + Global::config().get("jobs") + " for option -j/--jobs!");
+            }
+            Global::config().set("jobs", "0");
         }
+#else
+        // Check that -j option has not been changed from the default
+        if (Global::config().get("jobs") != "1") {
+            std::cerr << "\nWarning: OpenMP is not enabled\n";
```
Comment (lyndonhenry) [inline src/main.cpp]: Give instruction on how to enable OpenMP in error message.

File: src/main.cpp [hunk 4]
```diff
@@ -515,7 +510,7 @@ int main(int argc, char** argv) {
                     std::make_unique<HoistAggregateTransformer>(), std::make_unique<TupleIdTransformer>())),
             std::make_unique<ExpandFilterTransformer>(), std::make_unique<HoistConditionsTransformer>(),
             std::make_unique<RamConditionalTransformer>(
-                    []() -> bool { return std::stoi(Global::config().get("jobs")) > 1; },
+                    []() -> bool { return std::stoi(Global::config().get("jobs")) != 1; },
```
Comment (lyndonhenry) [inline src/main.cpp]: Provide comment about auto for a job count of 0.

File: src/main.cpp [hunk 5]
```diff
@@ -245,30 +245,25 @@ int main(int argc, char** argv) {
...
-            } else {
-                if (!Global::config().has("jobs", "auto")) {
-                    throw std::runtime_error(
-                            "Wrong parameter " + Global::config().get("jobs") + " for option -j/--jobs!");
-                }
-                Global::config().set("jobs", "0");
+        if (isNumber(Global::config().get("jobs").c_str())) {
+            if (std::stoi(Global::config().get("jobs")) < 1) {
+                throw std::runtime_error(
+                        "Number of jobs in the -j/--jobs options must be greater than zero!");
```
Comment (lyndonhenry) [inline src/main.cpp]: Or auto.

File: src/main.cpp (hunk 3 above)
Comment (mmcgr) [reply src/main.cpp]: Since it's not possible to just enable openmp, I changed the message to state that concurrent jobs aren't supported with that installation of souffle. (Requiring openmp to build souffle in the first place seems like a better option, though.)

**Comment by mmcgr** [comment]
Jenkins, test this please

**Comment by mmcgr** [comment]
Jenkins, test this please

**Comment by mmcgr** [comment]
Jenkins, test this please

**Comment by mmcgr** [comment]
Jenkins, test this please
