### PR TITLE
Fix segfault in ~ProfileEventSingleton

### LINKED ISSUE #2217: segfault when profiling
Souffle version: fce85d9ec8898a53365a0abb39485f27b14987b0

Command-line:
```
Starting program: /usr/local/bin/souffle -PSIPS:max-bound -j 24 -L .out/build/llvm -lFunctors llvm/PointerAnalysis/datalog/unification.project -F .out/cache/pointer-analysis/out.ll.facts -D .out/cache/pointer-analysis/out.ll.results -p prof.json
```
GDB backtrace:
```
Thread 1 "souffle" received signal SIGSEGV, Segmentation fault.
souffle::ProfileEventSingleton::dump (this=0x0)
    at ../src/include/souffle/profile/ProfileEvent.h:133
133	../src/include/souffle/profile/ProfileEvent.h: No such file or directory.
(gdb) bt
#0  souffle::ProfileEventSingleton::dump (this=0x0)
    at ../src/include/souffle/profile/ProfileEvent.h:133
#1  0x0000000000512009 in souffle::ProfileEventSingleton::~ProfileEventSingleton (
    this=0x234fa60) at ../src/include/souffle/profile/ProfileEvent.h:54
#2  0x0000000000511e58 in std::__1::default_delete<souffle::ProfileEventSingleton>::operator() (__ptr=0x234fa60, this=<optimized out>)
    at /usr/lib/llvm-10/bin/../include/c++/v1/memory:2363
#3  std::__1::unique_ptr<souffle::ProfileEventSingleton, std::__1::default_delete<souffle::ProfileEventSingleton> >::reset (this=<optimized out>, __p=0x0)
    at /usr/lib/llvm-10/bin/../include/c++/v1/memory:2618
#4  std::__1::unique_ptr<souffle::ProfileEventSingleton, std::__1::default_delete<souffle::ProfileEventSingleton> >::~unique_ptr (this=<optimized out>)
    at /usr/lib/llvm-10/bin/../include/c++/v1/memory:2572
#5  0x00007fa12bddfa27 in __run_exit_handlers (status=0, 
    listp=0x7fa12bf81718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, 
    run_dtors=run_dtors@entry=true) at exit.c:108
#6  0x00007fa12bddfbe0 in __GI_exit (status=<optimized out>) at exit.c:139
#7  0x00007fa12bdbd0ba in __libc_start_main (main=0x4c2de0 <main(int, char**)>, argc=14, 
    argv=0x7ffea0324318, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffea0324308) at ../csu/libc-start.c:342
#8  0x00000000004b554e in _start ()
```
Let me know if there's anything else I could post that would help - my program is quite large and I haven't taken the time to minimize it yet, but I'm happy to send it on over.

### PR DESCRIPTION
**Pull request by langston-barrett**
Fixes #2217. There's no need to call `::instance`, this destructor is already running on the singleton instance.

### CODE REVIEW

File: src/include/souffle/profile/ProfileEvent.h [hunk 1]
```diff
@@ -51,7 +51,7 @@ class ProfileEventSingleton {
 public:
     ~ProfileEventSingleton() {
         stopTimer();
```
Comment (b-scholz) [inline src/include/souffle/profile/ProfileEvent.h:53]: Do we need to do the same for stopTimer?

Comment (langston-barrett) [reply src/include/souffle/profile/ProfileEvent.h:53]: Not as far as I can tell - the call to `stopTimer` doesn't use the `instance` method, which I believe is what's causing the issue. Plus, it stopped segfaulting with this change as is.

**Comment by b-scholz** [comment]
We need to understand better what is going on. Is your library a static or a dynamic library?

**Review by b-scholz — APPROVED** [review]
Thanks for fixing!
