### PR TITLE
Stricter typesystem

### LINKED ISSUE #832: Subtyping not checked
The following code causes a crash instead of an error, since `number | symbol` is not a subtype of `number`:

```
.type X = number | symbol 
.type Y = number

.decl A(x : X)
A(1).

.decl B(x : Y)
B(x) :- A(x).

.output B(IO = stdout)
```

### PR DESCRIPTION
**Pull request by darth-tytus**
- Introduce stricter typing strategy (based on the idea of sinks and sources)
- Refactor type system (`TypeSystem` and `AstTypeAnalysis`)
- Add `legacy` flag to support old type constructs

Resolve #832 

Note: there are still some rough edges here. For example, the strategy of typing constants needs further work. There are no tests for legacy typing yet.

### CODE REVIEW

File: src/AstTypeAnalysis.cpp [hunk 1]
```diff
@@ -476,251 +432,244 @@ AstClause* createAnnotatedClause(
...
-            addConstraint(hasSuperTypeInSet(getVar(constant), possibleTypes));
         }
 
-        // binary constraint
-        void visitBinaryConstraint(const AstBinaryConstraint& rel) override {
-            auto lhs = getVar(rel.getLHS());
-            auto rhs = getVar(rel.getRHS());
-            addConstraint(isSubtypeOf(lhs, rhs));
-            addConstraint(isSubtypeOf(rhs, lhs));
+        // Debug report does not run the standard transformers.
```
Comment (mmcgr) [inline src/AstTypeAnalysis.cpp:561]: You could simplify this to just say "The type of the user-defined ...". The analysis is independent of the debug report.

File: src/AstTypeAnalysis.cpp [hunk 2]
```diff
@@ -476,251 +432,244 @@ AstClause* createAnnotatedClause(
...
+    os << "-- Result --" << std::endl;
+    for (const auto& cur : annotatedClauses) {
+        os << *cur << std::endl;
+    }
+}
+
+void TypeAnalysis::run(const AstTranslationUnit& translationUnit) {
+    // Check if debugging information is being generated
+    std::ostream* debugStream = nullptr;
+    if (Global::config().has("debug-report") || Global::config().get("show") == "type-analysis") {
```
Comment (mmcgr) [inline src/AstTypeAnalysis.cpp:656]: You can use `Global::config::has(key, value)` - something like:
```suggestion
    if (Global::config().has("debug-report") || Global::config().has("show", "type-analysis")) {
```
