### PR TITLE
Fold anonymous records

### LINKED ISSUE #837: Crash when comparing different sized records
The following program causes a crash as an assertion fails:
```
.decl A(x:number)
A(1) :- [1,2] = [1].
```
Note that following does not cause any crash, but outputs the wrong result (should output 1, instead get no output):
```
.decl A(x:number)
A(1) :- [1,2] != [1].
.output A(IO=stdout)
```

### PR DESCRIPTION
**Pull request by darth-tytus**
- Add transformers that reduce anonymous records to equalities/inequalities on their elements. 
This sidesteps the issue of extending the type system to handle anonymous records.

Fixes #837.

### CODE REVIEW

File: src/AstTransforms.cpp [hunk 1]
```diff
@@ -1414,4 +1414,289 @@ bool AstUserDefinedFunctorsTransformer::transform(AstTranslationUnit& translatio
...
+        return false;
+    }
+
+    // Check if operator is "=" or "!="
+    auto op = constraint->getOperator();
+    if (!isEqConstraint(op) && !isEqConstraint(negatedConstraintOp(op))) {
+        return false;
+    }
+
+    return true;
```
Comment (mmcgr) [inline src/AstTransforms.cpp:1446]: The linter would like this to be
```
    return !(!isEqConstraint(op) && !isEqConstraint(negatedConstraintOp(op)));
```
the simpler version seems preferable
```suggestion
    return isEqConstraint(op) || isEqConstraint(negatedConstraintOp(op));
```
